# Font settings
font_family MesloLGS Nerd Font Mono
font_size 12.0
bold_font auto
italic_font auto
bold_italic_font auto

# Opacity settings (background opacity)
background_opacity 0.85

# Display server settings (x11/wayland/auto)
linux_display_server wayland

# Padding settings (in pixels)
window_padding_width 15
window_padding_height 15

# Clipboard settings
copy_on_select yes

# Selection colors
selection_background_color rgba(255, 255, 255, 0.15) # Lighter selection background
selection_foreground_color black  # Set the selection text color to black for contrast
